// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpGEGaXNGq0iOm1oQw_Mjl6gfnc29eXCA',
    appId: '1:273094979556:web:5d99cda0333448d781a1f1',
    messagingSenderId: '273094979556',
    projectId: 'epicstream-33f51',
    authDomain: 'epicstream-33f51.firebaseapp.com',
    storageBucket: 'epicstream-33f51.firebasestorage.app',
    measurementId: 'G-2FLMQ95LHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvHJmH-aXt-gfdap1KFLbEinG0T3TLx60',
    appId: '1:273094979556:android:a93a64320365ded981a1f1',
    messagingSenderId: '273094979556',
    projectId: 'epicstream-33f51',
    storageBucket: 'epicstream-33f51.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD2dyr7XgXDS-Sm4N-YnezWjhhsA7sXiI',
    appId: '1:273094979556:ios:5f9a7e986cddc48781a1f1',
    messagingSenderId: '273094979556',
    projectId: 'epicstream-33f51',
    storageBucket: 'epicstream-33f51.firebasestorage.app',
    iosBundleId: 'com.manjunath.epicstream',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD2dyr7XgXDS-Sm4N-YnezWjhhsA7sXiI',
    appId: '1:273094979556:ios:5f9a7e986cddc48781a1f1',
    messagingSenderId: '273094979556',
    projectId: 'epicstream-33f51',
    storageBucket: 'epicstream-33f51.firebasestorage.app',
    iosBundleId: 'com.manjunath.epicstream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpGEGaXNGq0iOm1oQw_Mjl6gfnc29eXCA',
    appId: '1:273094979556:web:282ae2557e064bc681a1f1',
    messagingSenderId: '273094979556',
    projectId: 'epicstream-33f51',
    authDomain: 'epicstream-33f51.firebaseapp.com',
    storageBucket: 'epicstream-33f51.firebasestorage.app',
    measurementId: 'G-V73E27TM6G',
  );
}
